services:
  demo-app:
    build:
      context: ./app
    container_name: ${COMPOSE_PROJECT_NAME:-prom-demo}-demo-app-1
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME:-prom-demo}-nginx-1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: ${COMPOSE_PROJECT_NAME:-prom-demo}-nginx-exporter-1
    command: ["-nginx.scrape-uri", "http://nginx:8080/stub_status"]
    depends_on:
      - nginx
    ports:
      - "9113:9113"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${COMPOSE_PROJECT_NAME:-prom-demo}-node-exporter-1
    command:
      - --path.rootfs=/
    ports:
      - "9100:9100"
    restart: unless-stopped

  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    container_name: ${COMPOSE_PROJECT_NAME:-prom-demo}-otel-collector-1
    environment:
      - SPLUNK_CONFIG=/etc/otel/config.yaml
    env_file:
      - ../.env
    volumes:
      - ./otel-collector-config-prom-demo.yaml:/etc/otel/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    restart: unless-stopped
